version: "3"

services:
  web:
    environment:
      - CouncilTag=debug
      - DEBUG=True
      - DJANGO_SECRET_KEY=examplesecretkeydonotuseinprod
      - RECAPTCHAKEY=some_string
      - POSTGRES_USER=engageuser
      - POSTGRES_PASSWORD=engageuserpassword
      - POSTGRES_DB=counciltag
      - HOST=db
      - REDIS_URL=redis://redis:6379
      - AWS_ACCESS_KEY_ID="AKIAJHGBRQ5ZX6IUSX4A"
      - AWS_SECRET_ACCESS_KEY="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"
      - AWS_REGION="us-east-1"
    build: .
    command: python /engage_backend_service/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/engage_backend_service
    ports:
      - "8000:8000"
      - "443:443"
      - "80:80"
    depends_on:
      - db
      - redis
  db:
    image: postgres:10.5
  redis:
    image: redis:4.0.0
