version: 2
jobs:
  test:
    working_directory: ~/engage_backend_service
    machine: 
      enabled: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker-compose build
      # Not using -d since will exit after completion
      # Have to figure out how to shut down redis from entrypoint script
      - run: 
          name: Check test and upload if succeeded
          command: |
              docker-compose -f docker-compose-test.yml up --abort-on-container-exit --exit-code-from backend
              if [ $? -eq 0 ]; then; docker push hack4laengage/engage_backend_service; else; return 1; fi
      - store_test_results:
          path: ~/engage_backend_service/tmp/test-results
      - store_artifacts:
          path: ~/engage_backend_service/tmp/test-results
          destination: tr1
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
            fingerprints:
              - "dc:9f:48:96:a1:76:08:e3:f9:5b:2e:c1:1e:5b:06:5a"
      - run:
            name: Deploy over SSH
            command: |
                ssh -f $SSH_USER@$SSH_HOST "./deploy.sh"
workflows:
 version: 2
 build-and-deploy:
   jobs:
     - test
     - deploy:
         requires:
           - test
         filters:
           branches:
             only: master
